### ISSUE TITLE
enhancement - auto expand bitly links

### ISSUE THREAD

**Issue by johndpope** [sigriffiths/twitter-to-slack#1]
Hey Simon,

I spent the last couple of days faffing around looking for a solution to my problem (bip.io) - and your code base looks the closest fit to what I'm trying to do. I mostly program in  swift / objective -c.

I've got an existing twitter feed hooked up - but the links are all bit.ly (the creator is using some tracking codes and refuses to provide content) but consequently in slack they don't auto expand with graphics. 

was thinking of some regex for url detection 
http://www.regexguru.com/2008/11/detecting-urls-in-a-block-of-text/

and throw any bitly links against this api to auto expand -> 
http://longurl.org/api#api-endpoint

Then repost into slack. 

<img width="849" alt="screen shot 2015-09-23 at 1 48 05 pm" src="https://cloud.githubusercontent.com/assets/289994/10037466/bcc03d76-61f9-11e5-8c52-1a6ddfb55b85.png">

**Comment by sigriffiths** [comment]
Hey John,

As part of the tweet there is a whole slew of meta data returned part of which is an array of urls embedded within the tweet.

I'd suggest you simply iterate over that that and match on bit.ly then use something like https://github.com/tanepiper/node-bitly to expand the links you find.

You could inject this here:

```
        tweet.entities.urls.map(function(url) {
            tweet.text = tweet.text.replace(url.url,url.expanded_url);
        });
```

Hope this helps and let me know how you get on :+1:

**Comment by johndpope** [comment]
hacking away on another rss feed from google. 
trying to twist the links into shape using bip.io and have it spit an rss

![screen shot 2015-09-23 at 5 18 39 pm](https://cloud.githubusercontent.com/assets/289994/10039607/269e6f34-6217-11e5-8222-0e16f5b3f635.png)

**Comment by johndpope** [comment]
fyi https://bip.io/dash#/bipio/5afd3bea-f770-479e-819a-5fa64e0246c3

**Comment by johndpope** [comment]
@sigriffiths - thanks for your efforts here -
I'm closing out old github tickets in a spring cleaning exercise.
https://github.com/issues
126 to go.
